# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: issue.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'issue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import jsonschema_pb2 as jsonschema__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bissue.proto\x1a\x10jsonschema.proto\":\n\x07Message\x12/\n\x0b\x66oo_bar_baz\x18\x01 \x01(\x02\x42\x0f\xfa\xc4\x05\x0b\x62\t\x19\x00\x00\x00\x00\x00\x00\x00\x00R\tfooBarBazb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'issue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE'].fields_by_name['foo_bar_baz']._loaded_options = None
  _globals['_MESSAGE'].fields_by_name['foo_bar_baz']._serialized_options = b'\372\304\005\013b\t\031\000\000\000\000\000\000\000\000'
  _globals['_MESSAGE']._serialized_start=33
  _globals['_MESSAGE']._serialized_end=91
# @@protoc_insertion_point(module_scope)
